concurrent: 110
check-interval: 30
timeout: 5002
min-speed: 3000
download-timeout: 5
speed-test-url: https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/download/v2.21.12/Waifu2x-Extension-GUI-v2.21.12-Portable.7z
save-method: gist
github-gist-id: bfb9895db7be7bd7573ecb2bc7f6f3d8a9e685a8
github-token: 11AZKQ3XQ01qQzZnUOcaSI_Tei3lDOfcUx6xBmPXrA416lgntmzNMEZJB2C5hKb4auBF7THIJ2JMLpmHQp
github-api-mirror: api.github.fxxk.dedyn.io
worker-url: https://example.worker.dev
worker-token: 1234567890
webdav-username: admin
webdav-password: admin
webdav-url: https://example.com/dav/
enable-web-ui: true
listen-port: 127.0.0.1:8199
old-api-key: admin
api-key: f0827640c1af2e51fa16005da1dde9cd
sub-store-port: :8299
githubproxy: 自动选择
github-proxy: https://hub.885666.xyz/
sub-urls:
  - http://127.0.0.1:8199/all.yaml
  - https://raw.githubusercontent.com/aiboboxx/v2rayfree/main/v2
  - https://raw.githubusercontent.com/chengaopan/AutoMergePublicNodes/master/list.txt
mihomo-overwrite-url: http://127.0.0.1:8199/ACL4SSR_Online_Full.yaml
rename-node: true
media-check: false
keep-success-proxies: false
print-progress: false
sub-urls-retry: 3
subscheck-version: v2.3.2
gui-auto: false
success-limit: 0
